-- SEEDANCE 2.0 ELITE COLLECTION
INSERT INTO prompts (title, content, category, author, image_url, is_generated) VALUES
('Cinematic Japanese Romance', '15-second cinematic Japanese drama pure love ambiguous short film, ultra-realistic quality, warm golden sunlight in an empty classroom in the afternoon, spilling through the blinds onto the side-by-side desks, fine dust motes slowly floating in the light beams...', 'Video', '阳家豪', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/7f63ad253175a9ad1dac53de490efac8/thumbnails/thumbnail.jpg', TRUE),
('Haute Couture Fantasy', 'Hollywood Haute Couture Fantasy blockbuster, 8K ultra-clear, Photorealistic, High-fashion Editorial Style, Unreal Engine 5 fluid rendering, visual illusion. [Duration] 15 seconds. [Scene] An endless, real-life Salar de Uyuni (Sky Mirror) salt flat...', 'Video', 'John', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/e066fab457509bc6809ea212ae5d6a51/thumbnails/thumbnail.jpg', TRUE),
('Modern Rural Aesthetics', 'Modern Rural Aesthetics, Cinematic Commercial quality, shot with Sony A7S3/cinema camera, 4K/8K ultra-clear, Extreme Macro, natural transparent lighting, healing ASMR, no historical costume drama feel...', 'Video', 'John', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/ce508b28e505ffce07247e2ab036d6f1/thumbnails/thumbnail.jpg', TRUE),
('Anime Adaptation Duel', 'Live-Action Anime Adaptation · Breathing Technique Decisive Battle (15 seconds · Super Burning Special Effects Version). Water Breathing (Blue Water Dragon) VS Thunder Breathing (Golden Lightning), live-action extreme speed duel...', 'Video', 'John', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/870c9907c5740c3d98ed2d62328ca83b/thumbnails/thumbnail.jpg', TRUE),
('80-Year-Old Rapper MV', '16:9 horizontal screen, street rap MV style, neon purple and blue cool tones, explosive cool and fierce atmosphere. 80-year-old silver-haired woman stands in front of a graffiti wall, rapping with intense rhythm...', 'Video', '松果先森', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/e011d2666b5ee19d5b9f8b9837b974c2/thumbnails/thumbnail.jpg', TRUE),
('Street Racing Sequence', 'Cinematic street racing sequence at night, a focused driver inside a high-performance car grips the steering wheel, intense eye focus, city lights reflecting on windshield, tension building before sudden acceleration...', 'Video', 'Pierrick Chevallier', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/3a7fb0a6d706b9f568479bb720ce1ad4/thumbnails/thumbnail.jpg', TRUE),
('Cinematic Espresso Prep', 'A highly technical cinematography prompt outlining a detailed sequence for filming the preparation of a brown sugar cinnamon espresso, focusing on textures, lighting, and sound effects...', 'Video', '1LittleCoder', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/9243165f7b6836e17db18b63fb0e5d4e/thumbnails/thumbnail.jpg', TRUE),
('Garage CCTV Horror', '15-second cinematic horror sequence involving a strange being with prominent glowing eyes captured in the garage CCTV camera. Gritty, low-light, terrifying atmosphere...', 'Video', 'ReAiLity Labs', 'https://cms-assets.youmind.com/media/1777963520650_8373ya_HHft4wUW0AAUpNd.jpg', TRUE),
('Animated Dancing Bear', 'A cute animated bear dancing confidently in an open outdoor forest clearing during bright daytime, full body visible, smooth rhythmic dance movements, trendy streetwear...', 'Video', 'Aegon', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/19617759819dd0d20afcaad65e874507/thumbnails/thumbnail.jpg', TRUE),
('Shanghai Motorcycle Stunt', 'A stunt rider in a matte-black helmet accelerations a superbike along the narrow arm of a construction crane high above Shanghai’s skyline. Crane collapses, rider launches motorcycle across open air...', 'Video', 'LudovicCreator', 'https://customer-qs6wnyfuv0gcybzj.cloudflarestream.com/b5a00d2fa5d0d44cc33ca8d183f947c9/thumbnails/thumbnail.jpg', TRUE),
('Cyberpunk Neon Samurai', 'A cyberpunk neon-lit street with a cybernetic samurai standing in the rain. Raindrops hitting the glowing blade, reflections of neon signs in puddles, 8K ultra-realistic, cinematic lighting...', 'Art', 'Ecotron AI', NULL, FALSE),
('E-commerce Product Photo', 'Professional studio product photography of a minimalist white sneaker, floating in mid-air with soft shadows, clean marble background, 8K, high contrast, commercial quality...', 'Marketing', 'Ecotron AI', NULL, FALSE),
('Next.js API Handler', 'Write a robust Next.js API route handler using TypeScript and Zod for validation. Include error handling, rate limiting, and connection to a PostgreSQL database using Drizzle ORM...', 'Coding', 'Ecotron AI', NULL, FALSE),
('SaaS Landing Page Hero', 'Write a high-converting hero section for a B2B SaaS landing page focusing on AI-driven automation. Include a catchy headline, benefit-driven subheadline, and a clear CTA button...', 'Marketing', 'Ecotron AI', NULL, FALSE);
